/**
 * @file version.h
 * @brief Automatically generated version
 */

#pragma once

/**
 * Git branch/commit to be generated by cmake
 */

#define FP_GIT_BRANCH "add-pdlp-portfolio"
#define FP_GIT_HASH "041bc0d-dirty"
